site_name: 洇岚 帮助文档
theme:
  name: material
  logo: https://q1.qlogo.cn/g?b=qq&nk=2811520355&s=100
  language: zh
  features:
nav:
  - 洇岚の帮助文档: index.md
  - 快速认识洇岚: startUp.md
  - 配置直播提醒: auto.md
  # - 功能:
  #   - B站相关: intro/bilibili.md
  #   - 表情包: intro/bilibili.md
  #   - 娱乐: intro/bilibili.md
  - 更新日志: updateLog.md
  - 用户协议:
    - 最新: userAgreement
    - 2022年2月17日: userAgreement/20220217.md
  - 隐私政策:
    - 最新: privacy
    - 2022年2月17日: privacy/20220217.md
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde