name: Deploy to Server

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Setup Deploy Private Key
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
      - name: Connect to Server
        run: |
          ssh root@console.hk.colourfur.com -o StrictHostKeyChecking=no
          
      - name: Remote Build
        run: |
          sh ~/updateYinlanHelp.sh
